// <auto-generated />
using System;
using Api_Central_de_Erros.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Api_Central_de_Erros.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200721145211_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("Api_Central_de_Erros.Models.Log", b =>
                {
                    b.Property<int>("logId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("logId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("createdAt")
                        .HasColumnName("createdAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnName("description")
                        .HasColumnType("TEXT");

                    b.Property<string>("environment")
                        .IsRequired()
                        .HasColumnName("environment")
                        .HasColumnType("TEXT");

                    b.Property<int>("frequency")
                        .HasColumnName("frequency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("level")
                        .IsRequired()
                        .HasColumnName("level")
                        .HasColumnType("TEXT");

                    b.Property<string>("origin")
                        .IsRequired()
                        .HasColumnName("origin")
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasColumnType("TEXT");

                    b.Property<int>("userId")
                        .HasColumnName("userId")
                        .HasColumnType("INTEGER");

                    b.HasKey("logId");

                    b.HasIndex("userId");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("Api_Central_de_Erros.Models.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("userId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("createdAt")
                        .HasColumnName("createdAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnName("password")
                        .HasColumnType("TEXT");

                    b.HasKey("userId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Api_Central_de_Erros.Models.Log", b =>
                {
                    b.HasOne("Api_Central_de_Erros.Models.User", "User")
                        .WithMany("Logs")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
